Создал BaseTicketBuilder и TicketBuilder
hsse-bot/hsse-telegram-bot pull request #56
Opened 2023-11-25 12:19 UTC by Droid5555

2023-11-25 12:35 UTC, DenVot requested changes

2023-11-25 12:35 UTC, DenVot commented on material_help_service/helpers/BaseTicketBuilder.py
> +from material_help_service.data.db.entities.Ticket import Ticket
Лишний импорт

2023-11-25 12:35 UTC, DenVot commented on material_help_service/helpers/BaseTicketBuilder.py
> +class BaseTicketBuilder:
Класс должен быть [ABC](https://advpyneng.readthedocs.io/ru/latest/book/12_oop_inheritance/abc.html)

2023-11-25 12:35 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +        return Ticket(self)
Где инициализация полей новосозданного объекта?

2023-11-25 12:35 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +        self.attachments.append(self.attachment)
Возможно стоит создать новый объект класса как-нибудь так? Просто хранить публичное поле `attachment`, чтобы использовать как обычную переменную, как-то немного cringe

```py
ClassA(
  prop1 = val1,
  prop2 = val2,
  ...
)
```

2023-11-25 12:35 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +    attachments: List[TicketAttachment]
У тебя будет ошибка при попытке вызвать `with_attachment`, потому что ты его не инициализировал

2023-11-25 16:06 UTC, Droid5555 commented on material_help_service/helpers/BaseTicketBuilder.py
> +class BaseTicketBuilder:
Исправил

2023-11-25 16:06 UTC, Droid5555 commented on material_help_service/helpers/BaseTicketBuilder.py
> +from material_help_service.data.db.entities.Ticket import Ticket
Исправил

2023-11-25 16:06 UTC, Droid5555 commented on material_help_service/helpers/TicketBuilder.py
> +        return Ticket(self)
Исправил

2023-11-25 16:06 UTC, Droid5555 commented on material_help_service/helpers/TicketBuilder.py
> +        self.attachments.append(self.attachment)
Исправил

2023-11-25 16:41 UTC, DenVot requested changes

2023-11-25 16:41 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +        self.author_tg_id_: int = 0
Подчеркивание перед

```suggestion
_author_tg_id: int = 0
```

2023-11-25 21:12 UTC, Droid5555 commented on material_help_service/helpers/TicketBuilder.py
> +        self.author_tg_id_: int = 0
Исправил

2023-11-25 21:46 UTC, DenVot approved these changes

2023-11-26 09:18 UTC, DenVot requested changes

2023-11-26 09:18 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +        if ticket.created_at is None:
А здесь не должно быть `self`?

```suggestion
if self._created_at is None
```

2023-11-26 09:18 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +        if ticket.ticket_text == "":
А здесь не должно быть `self`?

```suggestion
if self._ticket_text == ""
```

2023-11-26 09:18 UTC, DenVot commented on material_help_service/helpers/TicketBuilder.py
> +        if not ticket.attachments:
Этого быть по факту не должно, т.к. вложений может и не быть

2023-11-26 09:21 UTC, DenVot approved these changes

2023-11-26 09:22 UTC, merged