Написал BaseTicketManager и MySqlTicketManager
hsse-bot/hsse-telegram-bot pull request #57
Opened 2023-11-28 11:19 UTC by Droid5555

2023-11-29 19:32 UTC, DenVot requested changes

2023-11-29 19:32 UTC, DenVot commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +            ticket.status = 1
Было бы неплохо ввести какие-то константы с говорящим именем, ибо не совсем понятно что такое "1"

2023-11-29 19:32 UTC, DenVot commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +        return ticket
`return` внутрь `with`

2023-12-01 11:28 UTC, Droid5555 commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +            # Все поля поодельности присвоить
ой))) кринжанул

2023-12-01 11:35 UTC, Droid5555 commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +            return tickets_list
done

2023-12-01 11:50 UTC, Droid5555 commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +        return ticket
done

2023-12-01 11:50 UTC, Droid5555 commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +            ticket.status = 1
done

2023-12-01 11:50 UTC, Droid5555 commented on material_help_service/data/services/BaseTicketManager.py
> +import abc
done

2023-12-02 08:39 UTC, DenVot requested changes

2023-12-02 09:48 UTC, Droid5555 commented on material_help_service/data/services/mysql/MySqlTicketManager.py
> +            ticket.is_paper_included = new_ticket.is_paper_included
done

2023-12-02 09:52 UTC, DenVot approved these changes

2023-12-02 09:53 UTC, merged